"use client";

import { useEffect, useRef, useState } from "react";
import { Check, ChevronUp, Plus, RefreshCw, SquarePen, Trash2 } from "lucide-react";
import IconActionButton from "@/components/ui/IconActionButton";
import { api, ApiClientError, type ContentSeries } from "@/lib/apiClient";
import { accentAlpha, color } from "@/lib/design/tokens";
import { useContentCategories } from "@/contexts/CategoryLabelsContext";
import { KNOWN_PLATFORMS } from "@/lib/social/types";

type Draft = {
  id?: string;
  label: string;
  description: string;
  weight: number;
  categoryIds: string[];
  platforms: string[];
};

function toDrafts(series: ContentSeries[]): Draft[] {
  return series.map((s) => ({
    id: s.id,
    label: s.label,
    description: s.description,
    weight: s.weight,
    categoryIds: s.categories.map((c) => c.id),
    platforms: s.platforms,
  }));
}

export default function SeriesPanel({ onSeriesChange }: { onSeriesChange?: (series: ContentSeries[]) => void }) {
  const categories = useContentCategories();
  const [drafts, setDrafts] = useState<Draft[]>([]);
  const [loaded, setLoaded] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  // Replié par défaut dès qu'il y a des séries, pour laisser la place à la bibliothèque —
  // seul un clic sur "Modifier" déplie le formulaire d'édition complet.
  const [expanded, setExpanded] = useState(false);
  // Contrairement aux catégories (toujours >= 2 après génération), 0 série est un résultat
  // légitime de l'IA — ce flag évite de redéclencher un appel LLM à chaque montage si c'est le cas.
  const hasAutoGenerated = useRef(false);

  function apply(series: ContentSeries[]) {
    setDrafts(toDrafts(series));
    onSeriesChange?.(series);
  }

  async function generate() {
    setGenerating(true);
    setError(null);
    try {
      const { series } = await api.generateContentSeries();
      apply(series);
      setExpanded(true); // laisse l'utilisateur relire/ajuster la proposition fraîche avant de l'enregistrer
    } catch (err) {
      setError(err instanceof ApiClientError ? err.message : "Génération impossible.");
    } finally {
      setGenerating(false);
    }
  }

  useEffect(() => {
    (async () => {
      const { series } = await api.getContentSeries();
      apply(series);
      setLoaded(true);
      if (series.length === 0 && !hasAutoGenerated.current) {
        hasAutoGenerated.current = true;
        await generate();
      }
    })();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  function updateField(index: number, field: "label" | "description" | "weight", value: string) {
    setDrafts((prev) =>
      prev.map((d, i) => (i === index ? { ...d, [field]: field === "weight" ? Number(value) : value } : d))
    );
  }

  function toggleCategory(index: number, categoryId: string) {
    setDrafts((prev) =>
      prev.map((d, i) =>
        i === index
          ? {
              ...d,
              categoryIds: d.categoryIds.includes(categoryId)
                ? d.categoryIds.filter((id) => id !== categoryId)
                : [...d.categoryIds, categoryId],
            }
          : d
      )
    );
  }

  function togglePlatform(index: number, platform: string) {
    setDrafts((prev) =>
      prev.map((d, i) =>
        i === index
          ? {
              ...d,
              platforms: d.platforms.includes(platform)
                ? d.platforms.filter((p) => p !== platform)
                : [...d.platforms, platform],
            }
          : d
      )
    );
  }

  function addSeries() {
    setDrafts((prev) => [
      ...prev,
      { label: "Nouvelle série", description: "", weight: 10, categoryIds: [], platforms: [] },
    ]);
  }

  function removeSeries(index: number) {
    setDrafts((prev) => prev.filter((_, i) => i !== index));
  }

  async function save() {
    if (drafts.some((d) => d.categoryIds.length === 0)) {
      setError("Chaque série doit être liée à au moins une catégorie de contenu.");
      return;
    }
    setSaving(true);
    setError(null);
    try {
      const { series } = await api.saveContentSeries(drafts);
      apply(series);
      setExpanded(false); // révèle la bibliothèque une fois les séries validées
    } catch (err) {
      setError(err instanceof ApiClientError ? err.message : "Erreur lors de l'enregistrement.");
    } finally {
      setSaving(false);
    }
  }

  if (!loaded) return null;

  return (
    <div
      style={{
        display: "inline-flex",
        flexDirection: "column",
        width: "fit-content",
        minWidth: 320,
        maxWidth: "100%",
        border: `1px solid ${accentAlpha(0.25)}`,
        background: accentAlpha(0.06),
        borderRadius: 14,
        padding: 16,
      }}
    >
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 4, gap: 12 }}>
        <div style={{ fontWeight: 600, fontSize: 14 }}>Séries récurrentes adaptées à ton activité</div>
        <div style={{ display: "flex", gap: 6, flexShrink: 0 }}>
          {!expanded && drafts.length > 0 && (
            <IconActionButton icon={SquarePen} variant="neutral" title="Modifier les séries" onClick={() => setExpanded(true)} size={32} />
          )}
          <IconActionButton
            icon={RefreshCw}
            variant="neutral"
            title="Régénérer avec l'IA"
            onClick={generate}
            disabled={generating}
            size={32}
          />
        </div>
      </div>
      {(expanded || drafts.length === 0) && (
        <p style={{ margin: "0 0 14px", fontSize: 12, color: color.textMuted }}>
          Un format récurrent et nommé (ex: &laquo;&nbsp;Le mythe du mercredi&nbsp;&raquo;), avec sa propre identité, rattaché à une ou plusieurs catégories de contenu. Une partie du calendrier peut rester hors série.
        </p>
      )}

      {error && <p style={{ margin: "0 0 10px", fontSize: 12, color: color.danger }}>{error}</p>}

      {drafts.length === 0 ? (
        <p style={{ margin: "0 0 14px", fontSize: 13, color: color.textMuted }}>
          Aucune série pour l&apos;instant — ton activité n&apos;en a peut-être pas besoin, ou ajoutes-en une manuellement.
        </p>
      ) : !expanded ? null : (
        <div style={{ display: "grid", gap: 14, marginBottom: 14 }}>
          {drafts.map((d, i) => (
            <div
              key={d.id ?? `new-${i}`}
              style={{ border: `1px solid ${color.inputBorder}`, borderRadius: 10, padding: 12, background: color.cardBg }}
            >
              <div style={{ display: "flex", gap: 8, alignItems: "center", marginBottom: 8 }}>
                <input
                  value={d.label}
                  onChange={(e) => updateField(i, "label", e.target.value)}
                  placeholder="Nom de la série"
                  style={{
                    flex: 1,
                    border: `1px solid ${color.inputBorder}`,
                    borderRadius: 8,
                    padding: "8px 10px",
                    fontSize: 13,
                    fontWeight: 600,
                    fontFamily: "inherit",
                    background: color.cardBg,
                  }}
                />
                <input
                  type="number"
                  min={0}
                  max={100}
                  value={d.weight}
                  onChange={(e) => updateField(i, "weight", e.target.value)}
                  style={{
                    width: 64,
                    border: `1px solid ${color.inputBorder}`,
                    borderRadius: 8,
                    padding: "8px 10px",
                    fontSize: 13,
                    fontFamily: "inherit",
                    background: color.cardBg,
                  }}
                />
                <span style={{ fontSize: 12, color: color.textFaint }}>%</span>
                <IconActionButton icon={Trash2} variant="danger" title="Retirer" onClick={() => removeSeries(i)} size={28} />
              </div>
              <input
                value={d.description}
                onChange={(e) => updateField(i, "description", e.target.value)}
                placeholder="Identité de la série : angle, ton, structure à respecter"
                style={{
                  width: "100%",
                  border: `1px solid ${color.inputBorder}`,
                  borderRadius: 8,
                  padding: "8px 10px",
                  fontSize: 13,
                  fontFamily: "inherit",
                  background: color.cardBg,
                  marginBottom: 8,
                }}
              />
              <div style={{ display: "flex", flexWrap: "wrap", gap: 6, marginBottom: 8 }}>
                {categories.map((c) => {
                  const active = d.categoryIds.includes(c.id);
                  return (
                    <button
                      key={c.id}
                      onClick={() => toggleCategory(i, c.id)}
                      style={{
                        fontSize: 11,
                        fontWeight: active ? 600 : 500,
                        color: active ? "oklch(0.48 0.2 292)" : color.textMuted,
                        background: active ? accentAlpha(0.12) : color.inputBg,
                        border: `1px solid ${active ? "oklch(0.6 0.15 292)" : color.inputBorder}`,
                        borderRadius: 20,
                        padding: "4px 10px",
                        cursor: "pointer",
                      }}
                    >
                      {c.label}
                    </button>
                  );
                })}
              </div>
              <div style={{ display: "flex", flexWrap: "wrap", gap: 6, alignItems: "center" }}>
                <span style={{ fontSize: 11, color: color.textFaint, marginRight: 2 }}>
                  {d.platforms.length === 0 ? "Tous les réseaux" : "Réseaux :"}
                </span>
                {KNOWN_PLATFORMS.map((p) => {
                  const active = d.platforms.includes(p.key);
                  return (
                    <button
                      key={p.key}
                      onClick={() => togglePlatform(i, p.key)}
                      style={{
                        fontSize: 11,
                        fontWeight: active ? 600 : 500,
                        color: active ? "oklch(0.48 0.2 292)" : color.textMuted,
                        background: active ? accentAlpha(0.12) : color.inputBg,
                        border: `1px solid ${active ? "oklch(0.6 0.15 292)" : color.inputBorder}`,
                        borderRadius: 20,
                        padding: "3px 9px",
                        cursor: "pointer",
                      }}
                    >
                      {p.label}
                    </button>
                  );
                })}
              </div>
            </div>
          ))}
        </div>
      )}

      {(expanded || drafts.length === 0) && (
        <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
          <IconActionButton
            icon={Plus}
            variant="neutral"
            title="Ajouter une série"
            onClick={() => {
              addSeries();
              setExpanded(true);
            }}
            size={32}
          />
          {expanded && (
            <IconActionButton icon={ChevronUp} variant="neutral" title="Réduire" onClick={() => setExpanded(false)} size={32} />
          )}
          <div style={{ flex: 1 }} />
          <IconActionButton icon={Check} variant="primary" title="Enregistrer" onClick={save} disabled={saving} size={32} />
        </div>
      )}
    </div>
  );
}
