"use client";

import { useEffect, useRef, useState } from "react";
import Button from "@/components/ui/Button";
import { api, ApiClientError, type ContentSeries } from "@/lib/apiClient";
import { accentAlpha, color } from "@/lib/design/tokens";
import { useContentCategories } from "@/contexts/CategoryLabelsContext";

type Draft = { id?: string; label: string; description: string; weight: number; categoryIds: string[] };

function toDrafts(series: ContentSeries[]): Draft[] {
  return series.map((s) => ({
    id: s.id,
    label: s.label,
    description: s.description,
    weight: s.weight,
    categoryIds: s.categories.map((c) => c.id),
  }));
}

export default function SeriesPanel() {
  const categories = useContentCategories();
  const [drafts, setDrafts] = useState<Draft[]>([]);
  const [loaded, setLoaded] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  // Contrairement aux catégories (toujours >= 2 après génération), 0 série est un résultat
  // légitime de l'IA — ce flag évite de redéclencher un appel LLM à chaque montage si c'est le cas.
  const hasAutoGenerated = useRef(false);

  async function generate() {
    setGenerating(true);
    setError(null);
    try {
      const { series } = await api.generateContentSeries();
      setDrafts(toDrafts(series));
    } catch (err) {
      setError(err instanceof ApiClientError ? err.message : "Génération impossible.");
    } finally {
      setGenerating(false);
    }
  }

  useEffect(() => {
    (async () => {
      const { series } = await api.getContentSeries();
      setDrafts(toDrafts(series));
      setLoaded(true);
      if (series.length === 0 && !hasAutoGenerated.current) {
        hasAutoGenerated.current = true;
        await generate();
      }
    })();
  }, []);

  function updateField(index: number, field: "label" | "description" | "weight", value: string) {
    setDrafts((prev) =>
      prev.map((d, i) => (i === index ? { ...d, [field]: field === "weight" ? Number(value) : value } : d))
    );
  }

  function toggleCategory(index: number, categoryId: string) {
    setDrafts((prev) =>
      prev.map((d, i) =>
        i === index
          ? {
              ...d,
              categoryIds: d.categoryIds.includes(categoryId)
                ? d.categoryIds.filter((id) => id !== categoryId)
                : [...d.categoryIds, categoryId],
            }
          : d
      )
    );
  }

  function addSeries() {
    setDrafts((prev) => [...prev, { label: "Nouvelle série", description: "", weight: 10, categoryIds: [] }]);
  }

  function removeSeries(index: number) {
    setDrafts((prev) => prev.filter((_, i) => i !== index));
  }

  async function save() {
    if (drafts.some((d) => d.categoryIds.length === 0)) {
      setError("Chaque série doit être liée à au moins une catégorie de contenu.");
      return;
    }
    setSaving(true);
    setError(null);
    try {
      const { series } = await api.saveContentSeries(drafts);
      setDrafts(toDrafts(series));
    } catch (err) {
      setError(err instanceof ApiClientError ? err.message : "Erreur lors de l'enregistrement.");
    } finally {
      setSaving(false);
    }
  }

  if (!loaded) return null;

  return (
    <div style={{ border: `1px solid ${accentAlpha(0.25)}`, background: accentAlpha(0.06), borderRadius: 14, padding: 16 }}>
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 4, gap: 12 }}>
        <div style={{ fontWeight: 600, fontSize: 14 }}>Séries récurrentes adaptées à ton activité</div>
        <button
          onClick={generate}
          disabled={generating}
          style={{
            fontSize: 12,
            fontWeight: 600,
            color: "oklch(0.48 0.2 292)",
            background: color.cardBg,
            border: "1px solid oklch(0.6 0.15 292)",
            borderRadius: 8,
            padding: "6px 10px",
            cursor: generating ? "default" : "pointer",
            flexShrink: 0,
          }}
        >
          {generating ? "Génération..." : "Régénérer avec l'IA"}
        </button>
      </div>
      <p style={{ margin: "0 0 14px", fontSize: 12, color: color.textMuted }}>
        Un format récurrent et nommé (ex: &laquo;&nbsp;Le mythe du mercredi&nbsp;&raquo;), avec sa propre identité, rattaché à une ou plusieurs catégories de contenu. Une partie du calendrier peut rester hors série.
      </p>

      {error && <p style={{ margin: "0 0 10px", fontSize: 12, color: color.danger }}>{error}</p>}

      {drafts.length === 0 ? (
        <p style={{ margin: "0 0 14px", fontSize: 13, color: color.textMuted }}>
          Aucune série pour l&apos;instant — ton activité n&apos;en a peut-être pas besoin, ou ajoutes-en une manuellement.
        </p>
      ) : (
        <div style={{ display: "grid", gap: 14, marginBottom: 14 }}>
          {drafts.map((d, i) => (
            <div
              key={d.id ?? `new-${i}`}
              style={{ border: `1px solid ${color.inputBorder}`, borderRadius: 10, padding: 12, background: color.cardBg }}
            >
              <div style={{ display: "flex", gap: 8, alignItems: "center", marginBottom: 8 }}>
                <input
                  value={d.label}
                  onChange={(e) => updateField(i, "label", e.target.value)}
                  placeholder="Nom de la série"
                  style={{
                    flex: 1,
                    border: `1px solid ${color.inputBorder}`,
                    borderRadius: 8,
                    padding: "8px 10px",
                    fontSize: 13,
                    fontWeight: 600,
                    fontFamily: "inherit",
                    background: color.cardBg,
                  }}
                />
                <input
                  type="number"
                  min={0}
                  max={100}
                  value={d.weight}
                  onChange={(e) => updateField(i, "weight", e.target.value)}
                  style={{
                    width: 64,
                    border: `1px solid ${color.inputBorder}`,
                    borderRadius: 8,
                    padding: "8px 10px",
                    fontSize: 13,
                    fontFamily: "inherit",
                    background: color.cardBg,
                  }}
                />
                <span style={{ fontSize: 12, color: color.textFaint }}>%</span>
                <button
                  onClick={() => removeSeries(i)}
                  title="Retirer"
                  style={{
                    border: "none",
                    background: "none",
                    color: color.danger,
                    cursor: "pointer",
                    fontSize: 16,
                    lineHeight: 1,
                    padding: "4px 6px",
                  }}
                >
                  ×
                </button>
              </div>
              <input
                value={d.description}
                onChange={(e) => updateField(i, "description", e.target.value)}
                placeholder="Identité de la série : angle, ton, structure à respecter"
                style={{
                  width: "100%",
                  border: `1px solid ${color.inputBorder}`,
                  borderRadius: 8,
                  padding: "8px 10px",
                  fontSize: 13,
                  fontFamily: "inherit",
                  background: color.cardBg,
                  marginBottom: 8,
                }}
              />
              <div style={{ display: "flex", flexWrap: "wrap", gap: 6 }}>
                {categories.map((c) => {
                  const active = d.categoryIds.includes(c.id);
                  return (
                    <button
                      key={c.id}
                      onClick={() => toggleCategory(i, c.id)}
                      style={{
                        fontSize: 11,
                        fontWeight: active ? 600 : 500,
                        color: active ? "oklch(0.48 0.2 292)" : color.textMuted,
                        background: active ? accentAlpha(0.12) : color.inputBg,
                        border: `1px solid ${active ? "oklch(0.6 0.15 292)" : color.inputBorder}`,
                        borderRadius: 20,
                        padding: "4px 10px",
                        cursor: "pointer",
                      }}
                    >
                      {c.label}
                    </button>
                  );
                })}
              </div>
            </div>
          ))}
        </div>
      )}

      <div style={{ display: "flex", gap: 8 }}>
        <button
          onClick={addSeries}
          style={{
            fontSize: 12,
            fontWeight: 600,
            color: color.textSecondary,
            background: "none",
            border: `1px dashed ${color.dashedBorder}`,
            borderRadius: 8,
            padding: "8px 12px",
            cursor: "pointer",
          }}
        >
          + Ajouter une série
        </button>
        <Button onClick={save} disabled={saving} style={{ padding: "8px 16px", fontSize: 13, marginLeft: "auto" }}>
          {saving ? "..." : "Enregistrer"}
        </Button>
      </div>
    </div>
  );
}
